# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc3e66ee0c2859157ec4f7b9b730475c1a274297218ed9c9e00076cc9b42fdf233f21a406b5186a6bdba955f760c49954425d66c28dfea624d98b9dc24fb842f

test:
  secret_key_base: d052eb802192c62ea0e82cffcee0936e5f288f4951b5707c562f222868091b1b40dce7d9954d0f4cc3ec82d49477415640a4e2eee022aa28f934375c263cf4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
